from __future__ import annotations

from prompts.research_workflow import RESEARCH_WORKFLOW_INSTRUCTIONS
from prompts.researcher_instructions import RESEARCHER_INSTRUCTIONS
from prompts.subagent_delegation import SUBAGENT_DELEGATION_INSTRUCTIONS 